### PR TITLE
[#5057] remove resource from collection with multiple versions

### LINKED ISSUE #5057: Deleting a resource from a collection fails
**Description of the bug**
Resources may not be removed from a collection when relation metadata (that is going to be deleted) is missing.

Steps to reproduce the bug:
1. Copy https://www.hydroshare.org/resource/38feeef698ca484b907b7b3eb84ad05b/
2. Enter edit mode
3. Delete the first resource in the collection, [Example Data II For Surface Water and Ocean Topography Hydrology Community Discharge (SWOT SHCQ)](https://www.hydroshare.org/resource/465672b67a6d467384eba0724ca979ea/)

**Expected behavior**
I expect the resource to be deleted from the collection

**Additional information**
I did some investigation, there is an error message in the response.
```
{"status": "error", 
"msg": "'NoneType' object has no attribute 'delete'", 
"metadata_status": "Insufficient to make public", 
"new_coverage_list": []}
```
It looks like this happens when there is missing relational metadata, I'd wager either of these delete causes could be the culprit and both should be handled better.  https://github.com/hydroshare/hydroshare/blob/develop/hs_collection_resource/views.py#L141-L147

If the relation metadata that we want to delete is already deleted, then move on.  Also, while in there, please update the log statement to include the stacktrace with `logger.exception` instead of `logger.error` https://github.com/hydroshare/hydroshare/blob/develop/hs_collection_resource/views.py#L207

### PR DESCRIPTION
**Pull request by devincowan**
Resolves #5057

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [x] Peer Code review and approval

### Positive Test Case
1. Create a collection
2. Add a resource to the collection
3. Create a new version of the collection
4. You can remove the resource from the new collection without error

### CODE REVIEW

**Comment by hydrocheck** [comment]
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5058](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5058)

File: irods/use-local-irods.sh [hunk 1]
```diff
@@ -34,7 +34,7 @@ if [[ "${1}" == "--persist" ]]; then
         mkdir -p /home/${USER}/icat2/vault
         mkdir -p /home/${USER}/icat2/pgdata
     fi
-    # Create ${IRODS_HOST} container from irods v.4.1.8
+    # Create ${IRODS_HOST} container from irods v.4.2.6
```
Comment (sblack-usu) [inline irods/use-local-irods.sh:37]: Did you intend to sneak in an irods upgrade with this PR?

File: hs_core/tasks.py [hunk 2]
```diff
@@ -641,7 +641,11 @@ def create_new_version_resource_task(ori_res_id, username, new_res_id=None):
         if ori_res.resource_type.lower() == "collectionresource":
             # clone contained_res list of original collection and add to new collection
             # note that new version collection will not contain "deleted resources"
-            new_res.resources.set(ori_res.resources.all())
+            ori_resources = ori_res.resources.all()
+            new_res.resources.set(ori_resources)
+            # set the isPartOf metadata on all of the contained resources so that they also point at the new col
+            for res in ori_resources:
+                res.metadata.create_element('relation', type=RelationTypes.isPartOf, value=new_res.get_citation())
```
Comment (sblack-usu) [inline hs_core/tasks.py:648]: Nice, you found the root issue!

File: hs_collection_resource/management/commands/fix_collection_version_missing_ispartof.py [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+class Command(BaseCommand):
+    help = "Add missing isPartOf relation to resources in a collection"
+
+    # Get the hasPart relations for all collections
+    # For each relation, get the resource that is part
+    # Check that the resource has a reverse relation (that it isPartOf the collection)
+
+    def handle(self, *args, **options):
+        collections = BaseResource.objects.filter(resource_type="CollectionResource").all()
```
Comment (sblack-usu) [inline hs_collection_resource/management/commands/fix_collection_version_missing_ispartof.py:14]: It might be useful to have a dry-run option.  It isn't a big deal either way.

File: irods/use-local-irods.sh (hunk 1 above)
Comment (devincowan) [reply irods/use-local-irods.sh:37]: just wanted to get things to build
but you're right I guess that's poor form to sneak it in here
once we merge this https://github.com/hydroshare/hydroshare/pull/5053, the iRods upgrade will make it into Develop

**Review by sblack-usu — APPROVED** [review]
