### PR TITLE
[#6221] Fix for resource sharing status when updating metadata

### LINKED ISSUE #6221: Sharing Status shows as private for public resources in edit mode after updating a metadata field
**Description of the bug**
Sharing Status shows as Private for Public resources after editing the title while in edit mode. Going back to view mode, the sharing status corrects back to Public. 

https://github.com/user-attachments/assets/c2e17591-97fd-4720-84c1-924a9affdd8f

Steps to reproduce the bug:
1. Go to a public resource you have edit access to
2. Click Edit to enter edit mode
3. Update the title and click save
4. See the status change for Sharing Status

**Expected behavior**
Sharing status display should stay Public when editing metadata in edit mode

### PR DESCRIPTION
**Pull request by pkdash**
### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

### Positive Test Case
1. Refer to issue #6221 for testing
2. Verify that the resource status changes to Private from Public when all content files are deleted.

### CODE REVIEW

**Comment by MSDrao** [comment]
I still see the issue persisting.


https://github.com/user-attachments/assets/26d7f1b0-d352-406e-824a-2263958a3b72

File: theme/static/js/resourceLandingAjax.js [hunk 1]
```diff
@@ -859,6 +862,15 @@ function get_folder_struct_ajax_submit(res_id, store_path) {
 
             if (can_be_public) {
                 $("#missing-metadata-or-file:not(.persistent)").fadeOut();
+                // Update the Vue.js manage-access component
+                if (typeof manageAccessApp !== 'undefined' && manageAccessApp.canChangeResourceFlags) {
+                    manageAccessApp.$data.canBePublicDiscoverable = true;
```
Comment (MSDrao) [inline theme/static/js/resourceLandingAjax.js]: manageAccessApp.$data.canBePublicDiscoverable is explicity set to true, It may be better to get it from the can_be_public value instead.

**Comment by pkdash** [comment]
@MSDrao Was wondering if you cleared the browser cache.

**Comment by MSDrao** [comment]
> @MSDrao Was wondering if you cleared the browser cache.

Yes, I re-tested after a hard refresh and a fresh local startup, and the screen recording I posted is from incognito window

**Comment by pkdash** [comment]
I again tested in different browsers and in incongnito/private window - seems to work

https://github.com/user-attachments/assets/00c5400f-19a5-423d-bd1e-f267171f99d0

**Comment by MSDrao** [comment]
> I again tested in different browsers and in incongnito/private window - seems to work

The issue persists only in Chrome and appears to be due to stale site cache. Works fine in Safari and Firefox. Looks good to me.

**Review by MSDrao — DISMISSED** [review]

**Review by MSDrao — APPROVED** [review]
